import Card from "../types/Card";

const cardset_genesis: Card[] = [
    {
        id: "01-001-01",
        type: "Deus",
        name: "Thanatos",
        pantheon: "Grego",
        title: "Ceifador das Sombras da Noite",
        age: "Noir",
        cost: 3,
        atk: 3,
        def: 3,
        rarity: "Lendária",
        variant: "Padrão",
        text: "[wings_icon] Voar\n[1_icon]: [name] ganha +1 atk",
    },
    {
        id: "01-002-01",
        type: "Deus",
        name: "Zeus",
        pantheon: "Grego",
        title: "Tropa de Choque",
        age: "Cyberpunk",
        cost: 4,
        atk: 4,
        def: 4,
        rarity: "Rara",
        variant: "Padrão",
    },
    {
        id: "01-003-01",
        type: "Deus",
        name: "Medusa",
        pantheon: "Grego",
        title: "Engrenagem Rastejante",
        age: "Steampunk",
        cost: 1,
        atk: 1,
        def: 2,
        rarity: "Comum",
        variant: "Padrão",
    },
    {
        id: "01-004-01",
        type: "Deus",
        name: "Thanatos",
        pantheon: "Grego",
        title: "Onda de Morte",
        age: "Pirata",
        cost: 3,
        atk: 3,
        def: 4,
        rarity: "Lendária",
        variant: "Padrão",
    },
    {
        id: "01-005-01",
        type: "Deus",
        name: "Medusa",
        pantheon: "Grego",
        title: "Rainha da Rede",
        age: "Cyberpunk",
        cost: 3,
        atk: 3,
        def: 4,
        rarity: "Lendária",
        variant: "Padrão",
    },
    {
        id: "01-006-01",
        type: "Deus",
        name: "Izanami",
        title: "Enfermeira dos Mortos",
        pantheon: "Japonês",
        age: "Faroeste",
        cost: 6,
        atk: 6,
        def: 6,
        rarity: "Épica",
        variant: "Padrão",
        text: "investida\n[western_icon]: [name] ganha +1 atk",
    },
    {
        id: "01-007-01",
        type: "Deus",
        name: "Zeus",
        pantheon: "Grego",
        title: "Engenheiro Elétrico",
        age: "Steampunk",
        cost: 3,
        atk: 3,
        def: 4,
        rarity: "Lendária",
        variant: "Padrão",
    },
    {
        id: "01-008-01",
        type: "Deus",
        name: "Jormungandr",
        pantheon: "Nórdico",
        title: "O Pesadelo",
        age: "Cyberpunk",
        cost: 8,
        atk: 8,
        def: 8,
        rarity: "Lendária",
        variant: "Padrão",
    },

    {
        id: "01-060-01",
        type: "Deus",
        name: "Izanami",
        pantheon: "Japonês",
        title: "Rainha dos Afogados",
        age: "Pirata",
        cost: 6,
        atk: 6,
        def: 6,
        rarity: "Épica",
        variant: "Padrão",
    },
    {
        id: "01-066-01",
        type: "Deus",
        name: "Izanami",
        pantheon: "Japonês",
        title: "Acompanhante da Morte",
        age: "Noir",
        cost: 6,
        atk: 6,
        def: 6,
        rarity: "Épica",
        variant: "Padrão",
    },
    {
        id: "01-666-01",
        type: "Deus",
        name: "Izanami",
        pantheon: "Japonês",
        title: "Trapaceira Escarlate",
        age: "Cyberpunk",
        cost: 6,
        atk: 6,
        def: 6,
        rarity: "Rara",
        variant: "Padrão",
    },
    // {
    //     id: "01-666-02",
    //     type: "Deus",
    //     name: "Izanami",
    //     pantheon: "Japonês",
    //     title: "Trapaceira Escarlate",
    //     age: "Cyberpunk",
    //     cost: 6,
    //     atk: 6,
    //     def: 6,
    //     rarity: "Rara",
    //     variant: "Holográfica",
    // },
];

const cardset_second: Card[] = [];

export default [...cardset_genesis, ...cardset_second];
